  - block:
    - name: set apt key
      become: true
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present


    - name: Ensure the database service is running
      service:
        name: postgresql
        state: started
        enabled: true
      become: true

    - name: Create database user
      postgresql_user:
        name: paul
        password: democracyIsFragile
        role_attr_flags: CREATEDB,LOGIN
        state: present
      become: true
      become_user: postgres

    - name: Create database
      postgresql_db:
        name: paul
        owner: paul
        state: present
      become: true
      become_user: postgres