
- name: Create directory for poll
  file:
    path: /home/poll
    state: directory
    mode: 0755

- name: Archive poll
  unarchive:
    src: poll.tar
    dest: /home/poll/

- name: install virtualenv
  apt:
    name: virtualenv
    state: present

- name: Create virtualenv
  pip :
    virtualenv: /home/poll/venv
    requirements: /home/poll/poll/requirements.txt

- name: Install service
  template:
    src: ../poll/files/poll.service
    dest: /etc/systemd/system/poll.service
    mode: 0644
    owner: root
    group: root

- name: deamond reload service
  systemd:
    daemon_reload: true

- name: Enable service
  systemd:
    name: poll.service
    enabled: true
    state: started
